---
  - name: Get PostgreSQL encrypted secrets
    shell: "oc get secrets postgresql -n {{ namespace }} -o=jsonpath='{.data.database-password}'"
    register: postgresql_pwd_encrypt

  - name: Decrypt PostgreSQL encrypted secrets
    shell: "echo {{ postgresql_pwd_encrypt.stdout.strip() }} |base64 -d"
    register: postgresql_pwd
    when: postgresql_pwd_encrypt is defined

  - set_fact:
      postgresql_password: "{{ postgresql_pwd.stdout }}"

  - name: "create route for PostgreSQL metrics-exporter"
    k8s:
      state: present
      definition:
        kind: Route
        apiVersion: v1
        metadata:
          name: postgres-metrics-exporter
          namespace: "{{ namespace }}"
          labels:
            app: thoth
            component: postgres-metrics-exporter
        spec:
          to:
            kind: Service
            name: postgres-metrics-exporter

  - name: "create PostgreSQL metrics-exporter service"
    k8s:
      state: present
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          labels:
            service: postgres-metrics-exporter
            app: thoth
            component: postgres-metrics-exporter
          name: postgres-metrics-exporter
          namespace: "{{ namespace }}"
        spec:
          ports:
          - port: 80
            protocol: TCP
            targetPort: 9187
          selector:
            service: postgres-metrics-exporter

  - name: "create deployment config for PostgreSQL metrics-exporter"
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: DeploymentConfig
        metadata:
          labels:
            service:  postgres-metrics-exporter
            app: thoth
            component:  postgres-metrics-exporter
          name:  postgres-metrics-exporter
          namespace: "{{ namespace }}"
        spec:
          replicas: 1
          selector:
            service:  postgres-metrics-exporter
          template:
            metadata:
              labels:
                service:  postgres-metrics-exporter
            spec:
              containers:
            - name: "postgresql-metrics-exporter"
              image: wrouesnel/postgres_exporter
              env:
                - name: DATA_SOURCE_NAME
                  value: "postgresql://{{ postgresql_user }}:{{ postgresql_password }}@postgresql:5432/{{ postgresql_database }}?sslmode=disable"
              ports:
                - containerPort: 9187
                  protocol: TCP
                resources:
                  requests:
                    memory: "256Mi"
                    cpu: "1"
                  limits:
                    memory: "512Mi"
                    cpu: "1"
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /metrics
                  port: 9187
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 60
                successThreshold: 1
                timeoutSeconds: 10
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /metrics
                  port: 9187
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
          test: false
